import type { Product } from "./crm-data";

export const seedProducts: Product[] = [
  {
    "id": "AIR-MIDEA-0001",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea VRF Outdoor 25 KW MDV-V244WN1(AU)-R",
    "brandName": "Midea",
    "model": "MDV-V244WN1(AU)-R",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - variable refrigerant flow",
    "productUnitMount": "Outdoor",
    "gemsClass": "",
    "heatingCapacity": "25.0000",
    "coolingCapacity": "25.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - variable refrigerant flow - Outdoor - 25.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0002",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea VRF Indoor Unit 8KW MIH80GHN18-A",
    "brandName": "Midea",
    "model": "MIH80GHN18-A",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - variable refrigerant flow",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "8.0000",
    "coolingCapacity": "8.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - variable refrigerant flow - Wall Hung mount - 8.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0003",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea VRF Indoor 7.1 KW MIH71GHN18",
    "brandName": "Midea",
    "model": "MIH71GHN18",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - variable refrigerant flow",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "7.1000",
    "coolingCapacity": "7.1000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - variable refrigerant flow - Wall Hung mount - 7.10 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0004",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea VRF Indoor 5.6 KW MIH56GHN18",
    "brandName": "Midea",
    "model": "MIH56GHN18",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - variable refrigerant flow",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "5.6000",
    "coolingCapacity": "5.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - variable refrigerant flow - Wall Hung mount - 5.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0005",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea VRF Indoor 4.5 KW MIH45GHN18",
    "brandName": "Midea",
    "model": "MIH45GHN18",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - variable refrigerant flow",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "4.5000",
    "coolingCapacity": "4.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - variable refrigerant flow - Wall Hung mount - 4.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0006",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea VRF Indoor 3.6 KW MIH36GHN18",
    "brandName": "Midea",
    "model": "MIH36GHN18",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - variable refrigerant flow",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "3.6000",
    "coolingCapacity": "3.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - variable refrigerant flow - Wall Hung mount - 3.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0007",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea VRF Indoor 2.8 KW MIH28GHN18",
    "brandName": "Midea",
    "model": "MIH28GHN18",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - variable refrigerant flow",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "2.8000",
    "coolingCapacity": "2.8000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - variable refrigerant flow - Wall Hung mount - 2.80 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0008",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Outdoor 19 kw MULMI0619B",
    "brandName": "Midea",
    "model": "MULMI0619B",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Outdoor",
    "gemsClass": "",
    "heatingCapacity": "19.0000",
    "coolingCapacity": "19.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Outdoor - 19.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0009",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Indoor 8 kw MFAG80VA-N",
    "brandName": "Midea",
    "model": "MFAG80VA-N",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "8.0000",
    "coolingCapacity": "8.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 8.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0010",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Indoor 7 kw MFAG70VA-N",
    "brandName": "Midea",
    "model": "MFAG70VA-N",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "7.0000",
    "coolingCapacity": "7.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 7.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0011",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Indoor 5 kw MFAG51VA-N",
    "brandName": "Midea",
    "model": "MFAG51VA-N",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0012",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Indoor 3.6 kw MFAG36VA-N",
    "brandName": "Midea",
    "model": "MFAG36VA-N",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "3.6000",
    "coolingCapacity": "3.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 3.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0013",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Indoor 2.6 kw MFAG26VA-N",
    "brandName": "Midea",
    "model": "MFAG26VA-N",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "2.6000",
    "coolingCapacity": "2.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 2.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0014",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Outdoor 19KW MON6H19B1TA",
    "brandName": "Rinnai",
    "model": "MON6H19B1TA",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Outdoor",
    "gemsClass": "",
    "heatingCapacity": "19.0000",
    "coolingCapacity": "19.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Outdoor - 19.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0015",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Indoor 8KW HINRPX80M",
    "brandName": "Rinnai",
    "model": "HINRPX80M",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "8.0000",
    "coolingCapacity": "8.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 8.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0016",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Indoor 5KW HINRPX50M",
    "brandName": "Rinnai",
    "model": "HINRPX50M",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0017",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Indoor 3.5KW HINRPX35M",
    "brandName": "Rinnai",
    "model": "HINRPX35M",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "3.5000",
    "coolingCapacity": "3.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 3.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0018",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Indoor 2.5KW HINRPX25M",
    "brandName": "Rinnai",
    "model": "HINRPX25M",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "2.5000",
    "coolingCapacity": "2.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 2.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-CARRIER-0019",
    "category": "Aircon",
    "productClass": "",
    "productName": "Carrier Outdoor 19KW 38QUM190D8S6",
    "brandName": "Carrier",
    "model": "38QUM190D8S6",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Outdoor",
    "gemsClass": "",
    "heatingCapacity": "19.0000",
    "coolingCapacity": "19.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Outdoor - 19.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-CARRIER-0020",
    "category": "Aircon",
    "productClass": "",
    "productName": "Carrier Indoor 8KW 42QAG080N8",
    "brandName": "Carrier",
    "model": "42QAG080N8",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "8.0000",
    "coolingCapacity": "8.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 8.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-CARRIER-0021",
    "category": "Aircon",
    "productClass": "",
    "productName": "Carrier Indoor 5KW 42QAG050N8",
    "brandName": "Carrier",
    "model": "42QAG050N8",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-CARRIER-0022",
    "category": "Aircon",
    "productClass": "",
    "productName": "Carrier Indoor 3.5KW 42QAG035N8",
    "brandName": "Carrier",
    "model": "42QAG035N8",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "3.5000",
    "coolingCapacity": "3.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 3.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-CARRIER-0023",
    "category": "Aircon",
    "productClass": "",
    "productName": "Carrier Indoor 2.6KW 42QAG026N8",
    "brandName": "Carrier",
    "model": "42QAG026N8",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "2.6000",
    "coolingCapacity": "2.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 2.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-PANASONIC-0024",
    "category": "Aircon",
    "productClass": "",
    "productName": "Panasonic Outdoor 10KW CU-5Z100VBR",
    "brandName": "Panasonic",
    "model": "CU-5Z100VBR",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Outdoor",
    "gemsClass": "",
    "heatingCapacity": "10.0000",
    "coolingCapacity": "10.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Outdoor - 10.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-PANASONIC-0025",
    "category": "Aircon",
    "productClass": "",
    "productName": "Panasonic Indoor 7.1KW CS-RZ71XKR",
    "brandName": "Panasonic",
    "model": "CS-RZ71XKR",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "7.1000",
    "coolingCapacity": "7.1000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 7.10 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-PANASONIC-0026",
    "category": "Aircon",
    "productClass": "",
    "productName": "Panasonic Indoor 5KW CS-RZ50XKR",
    "brandName": "Panasonic",
    "model": "CS-RZ50XKR",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-PANASONIC-0027",
    "category": "Aircon",
    "productClass": "",
    "productName": "Panasonic Indoor 4.2KW CS-RZ42XKR",
    "brandName": "Panasonic",
    "model": "CS-RZ42XKR",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "4.2000",
    "coolingCapacity": "4.2000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 4.20 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-PANASONIC-0028",
    "category": "Aircon",
    "productClass": "",
    "productName": "Panasonic Indoor 3.5KW CS-RZ35XKR",
    "brandName": "Panasonic",
    "model": "CS-RZ35XKR",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "3.5000",
    "coolingCapacity": "3.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 3.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-PANASONIC-0029",
    "category": "Aircon",
    "productClass": "",
    "productName": "Panasonic Indoor 2.5KW CS-RZ25XKR",
    "brandName": "Panasonic",
    "model": "CS-RZ25XKR",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "2.5000",
    "coolingCapacity": "2.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 2.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0030",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Outdoor 12KW MXZ-6F120VG",
    "brandName": "Mitsubishi",
    "model": "MXZ-6F120VG",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Outdoor",
    "gemsClass": "",
    "heatingCapacity": "12.0000",
    "coolingCapacity": "12.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Outdoor - 12.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0031",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Indoor 7KW MSZ-AP71VGD",
    "brandName": "Mitsubishi",
    "model": "MSZ-AP71VGD",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "7.0000",
    "coolingCapacity": "7.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 7.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0032",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Indoor 5KW MSZ-AP50VGD",
    "brandName": "Mitsubishi",
    "model": "MSZ-AP50VGD",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0033",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Indoor 3.5KW MSZ-AP35VGD",
    "brandName": "Mitsubishi",
    "model": "MSZ-AP35VGD",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "3.5000",
    "coolingCapacity": "3.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 3.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0034",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Indoor 2.5KW MSZ-AP25VGD",
    "brandName": "Mitsubishi",
    "model": "MSZ-AP25VGD",
    "productType": "Non-Ducted",
    "productConfiguration": "Multiple split - fixed head",
    "productUnitMount": "Wall Hung",
    "gemsClass": "",
    "heatingCapacity": "2.5000",
    "coolingCapacity": "2.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Multiple split - fixed head - Wall Hung mount - 2.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0035",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Ducted Indoor Unit 25kW MIH224T1HN18(S)",
    "brandName": "Midea",
    "model": "MIH224T1HN18(S)",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "25.0000",
    "coolingCapacity": "25.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 25.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0036",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Ducted Outdoor Unit 25kW MDV-V250WN1D(AU)-R",
    "brandName": "Midea",
    "model": "MDV-V250WN1D(AU)-R",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Outdoor",
    "gemsClass": "",
    "heatingCapacity": "25.0000",
    "coolingCapacity": "25.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Outdoor - 25.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0037",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Ducted 18KW DONSR18B1/DINLR18B1",
    "brandName": "Rinnai",
    "model": "DONSR18B1/DINLR18B1",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "18.0000",
    "coolingCapacity": "18.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 18.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-HISENSE-0038",
    "category": "Aircon",
    "productClass": "",
    "productName": "Hisense Ducted 18KW AUW-180U4RZ1/AUD-180U4RSH1",
    "brandName": "Hisense",
    "model": "AUW-180U4RZ1/AUD-180U4RSH1",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "18.0000",
    "coolingCapacity": "18.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 18.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-HISENSE-0039",
    "category": "Aircon",
    "productClass": "",
    "productName": "Hisense Ducted 16KW AUW-160U4RH1/AUD-160UX4RSH1",
    "brandName": "Hisense",
    "model": "AUW-160U4RH1/AUD-160UX4RSH1",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "16.0000",
    "coolingCapacity": "16.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 16.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-CARRIER-0040",
    "category": "Aircon",
    "productClass": "",
    "productName": "Carrier Ducted 17KW 38QSH170D8S/42QSH170D8S",
    "brandName": "Carrier",
    "model": "38QSH170D8S/42QSH170D8S",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "17.0000",
    "coolingCapacity": "17.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 17.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-PANASONIC-0041",
    "category": "Aircon",
    "productClass": "",
    "productName": "Panasonic Ducted 18KW -U- 180PZH3R5/S-180PE4R",
    "brandName": "Panasonic",
    "model": "U- 180PZH3R5/S-180PE4R",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "18.0000",
    "coolingCapacity": "18.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 18.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0042",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Ducted 20KW PUZ-ZM200YKA-A/PEA-M200LAA",
    "brandName": "Mitsubishi",
    "model": "PUZ-ZM200YKA-A/PEA-M200LAA",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "20.0000",
    "coolingCapacity": "20.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 20.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0043",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Ducted 18KW PUZ-ZM180VKA-A/PEA-M180LAA",
    "brandName": "Mitsubishi",
    "model": "PUZ-ZM180VKA-A/PEA-M180LAA",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "18.0000",
    "coolingCapacity": "18.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 18.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0044",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Ducted 16KW PUZ-ZM160VKA-A/PEA-M160HAA",
    "brandName": "Mitsubishi",
    "model": "PUZ-ZM160VKA-A/PEA-M160HAA",
    "productType": "Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "Ducted",
    "gemsClass": "",
    "heatingCapacity": "16.0000",
    "coolingCapacity": "16.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Ducted - Single split system - Ducted - 16.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0045",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Single Split 8kW MFAG80VA-N/MFAG80VA-W",
    "brandName": "Midea",
    "model": "MFAG80VA-N/MFAG80VA-W",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "8.0000",
    "coolingCapacity": "8.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 8.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0046",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Single Split 7kW MFAG70VA-N/MFAG70VA-W",
    "brandName": "Midea",
    "model": "MFAG70VA-N/MFAG70VA-W",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "7.0000",
    "coolingCapacity": "7.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 7.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0047",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Single Split 5kW MFAG51VA-N/MFAG51VA-W",
    "brandName": "Midea",
    "model": "MFAG51VA-N/MFAG51VA-W",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0048",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Single Split 3.6kW MFAG36VA-N/MFAG36VA-W",
    "brandName": "Midea",
    "model": "MFAG36VA-N/MFAG36VA-W",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "3.6000",
    "coolingCapacity": "3.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 3.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MIDEA-0049",
    "category": "Aircon",
    "productClass": "",
    "productName": "Midea Single Split 2.6kW MFAG26VA-N/MFAG26VA-W",
    "brandName": "Midea",
    "model": "MFAG26VA-N/MFAG26VA-W",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "2.6000",
    "coolingCapacity": "2.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 2.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0050",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Single Split 8kW HSNRP80B",
    "brandName": "Rinnai",
    "model": "HSNRP80B",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "8.0000",
    "coolingCapacity": "8.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 8.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0051",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Single Split 7kW HSNRP70B",
    "brandName": "Rinnai",
    "model": "HSNRP70B",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "7.0000",
    "coolingCapacity": "7.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 7.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0052",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Single Split 5kW HSNRP50B",
    "brandName": "Rinnai",
    "model": "HSNRP50B",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0053",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Single Split 3.5kW HSNRP35B",
    "brandName": "Rinnai",
    "model": "HSNRP35B",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "3.5000",
    "coolingCapacity": "3.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 3.50 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-RINNAI-0054",
    "category": "Aircon",
    "productClass": "",
    "productName": "Rinnai Single Split 2.6kW HSNRP26B",
    "brandName": "Rinnai",
    "model": "HSNRP26B",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "2.6000",
    "coolingCapacity": "2.6000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 2.60 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0055",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Electric Single Split 7kW MUZ-AP71VGD2/MSZ-AP71VGD2",
    "brandName": "Mitsubishi",
    "model": "MUZ-AP71VGD2/MSZ-AP71VGD2",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "7.0000",
    "coolingCapacity": "7.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 7.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0056",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Electric Single Split 5kW MUZ-AP50VGD2/MSZ-AP50VGD2",
    "brandName": "Mitsubishi",
    "model": "MUZ-AP50VGD2/MSZ-AP50VGD2",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "5.0000",
    "coolingCapacity": "5.0000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 5.00 kW capacity",
    "price": 0
  },
  {
    "id": "AIR-MITSUBISHI-0057",
    "category": "Aircon",
    "productClass": "",
    "productName": "Mitsubishi Electric Single Split 2.5kW MUZ-AP25VGD2/MSZ-AP25VGD2",
    "brandName": "Mitsubishi",
    "model": "MUZ-AP25VGD2/MSZ-AP25VGD2",
    "productType": "Non-Ducted",
    "productConfiguration": "Single split system",
    "productUnitMount": "N/A",
    "gemsClass": "",
    "heatingCapacity": "2.5000",
    "coolingCapacity": "2.5000",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Non-Ducted - Single split system - 2.50 kW capacity",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0001",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy EE-HWS-A1-270",
    "brandName": "Emerald",
    "model": "EE-HWS-A1-270",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 270L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 270L tank",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0002",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy EE-HWS-A1-270E",
    "brandName": "Emerald",
    "model": "EE-HWS-A1-270E",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 270L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 270L tank",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0003",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy EE-HWS-A1-320",
    "brandName": "Emerald",
    "model": "EE-HWS-A1-320",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 320L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 320L tank",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0004",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy EE-HWS-A1-320-1",
    "brandName": "Emerald",
    "model": "EE-HWS-A1-320-1",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 320L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 320L tank",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0005",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy EE-HWS-A1-320E",
    "brandName": "Emerald",
    "model": "EE-HWS-A1-320E",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 320L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 320L tank",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0006",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy EE-HWS-A1-320E-1",
    "brandName": "Emerald",
    "model": "EE-HWS-A1-320E-1",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 320L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 320L tank",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0007",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy HPA1-S270",
    "brandName": "Emerald",
    "model": "HPA1-S270",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 270L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 270L tank",
    "price": 0
  },
  {
    "id": "HP-EMERALD-0008",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Emerald Energy HPA1-S270E",
    "brandName": "Emerald",
    "model": "HPA1-S270E",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 270L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 270L tank",
    "price": 0
  },
  {
    "id": "HP-POWERBAY-0009",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Power Bay PBG2-300RE-HYBRID",
    "brandName": "Powerbay",
    "model": "PBG2-300RE-HYBRID",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 300L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 300L tank",
    "price": 0
  },
  {
    "id": "HP-NEO-POWER-0010",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Neopower NA37-315A",
    "brandName": "Neo power",
    "model": "NA37-315A",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 315L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 315L tank",
    "price": 0
  },
  {
    "id": "HP-MIDEA-0011",
    "category": "Heat Pump",
    "productClass": "",
    "productName": "Midea RSJ-23/300RDN7-L2",
    "brandName": "Midea",
    "model": "RSJ-23/300RDN7-L2",
    "productType": "Hot Water System",
    "productConfiguration": "Heat Pump Hot Water - 300L",
    "productUnitMount": "Tank",
    "gemsClass": "",
    "heatingCapacity": "",
    "coolingCapacity": "",
    "aeER": "",
    "acop": "",
    "gemsHspfMixed": "",
    "gemsTcspfCold": "",
    "gemsTcspfMixed": "",
    "refrigerant": "",
    "status": "Approved",
    "imageUrl": "",
    "description": "Heat Pump Hot Water System - 300L tank",
    "price": 0
  }
];
